// qa-edge-cases.test.ts — critical-path gaps and undocumented edge cases (QA pass, 2026-09-24).
//
// Two kinds of test live here:
//
//   * Plain tests close a gap that mutation testing proved: a deliberate bug in the guard survived
//     the rest of the suite (see scripts/mutation-check.mjs; each test names the mutant it kills).
//   * `{ todo: "DEFECT-n …" }` tests assert the behaviour the library's own contract promises and
//     currently FAIL. node:test reports them without failing the run, so every confirmed defect
//     stays visible in the output until it is fixed — at which point delete the `todo`.

import { test } from "node:test";
import assert from "node:assert/strict";

import { DEFAULT_HARD_CAP_USD, estimateCostUsd, evaluateBudget } from "../src/budget-gate.ts";
import { evaluateRelease } from "../src/approval-gate.ts";
import { checkDisclosures } from "../src/disclosure.ts";
import { estimateMaxCostUsd, evaluateReservation } from "../src/reservation-gate.ts";
import { evaluateLoop } from "../src/loop-gate.ts";

const AD = { requireAd: true };
const AI = { requireAiGenerated: true };

// ── disclosure guard: every alternative, tested ALONE ───────────────────────
// Before this file, 7 of the 8 marker alternatives could be deleted without a single test failing,
// because every positive case happened to match #ad or #aigenerated. Each input below matches
// exactly one alternative, so each one pins exactly one pattern.

test("ad marker: #ad at the start, and after an opening bracket", () => {
  assert.equal(checkDisclosures("#ad Honest review.", AD).allowed, true);
  assert.equal(checkDisclosures("Honest review (#ad).", AD).allowed, true);
});

test("ad marker: 'paid partnership' alone is a disclosure", () => {
  // kills D2
  assert.equal(checkDisclosures("Paid partnership with Acme.", AD).allowed, true);
});

test("ad marker: 'affiliate link(s)' alone is a disclosure", () => {
  // kills D3
  assert.equal(checkDisclosures("This post contains affiliate links.", AD).allowed, true);
});

test("ad marker: 'sponsored' alone is a disclosure, in any case", () => {
  // kills D4 (deleted) and D11 (made case-sensitive)
  assert.equal(checkDisclosures("Sponsored.", AD).allowed, true);
  assert.equal(checkDisclosures("SPONSORED CONTENT", AD).allowed, true);
});

test("ad marker: a hashtag glued to a preceding word does not count", () => {
  // kills D1: without the prefix class, "broadcast#ad" would read as a disclosure.
  assert.equal(checkDisclosures("See the broadcast#ad schedule.", AD).allowed, false);
});

test("AI marker: #AI alone is a disclosure", () => {
  // kills D6
  assert.equal(checkDisclosures("Weekly roundup. #AI", AI).allowed, true);
});

test("AI marker: 'AI-generated' alone is a disclosure", () => {
  // kills D7
  assert.equal(checkDisclosures("This summary is AI-generated.", AI).allowed, true);
});

test("AI marker: 'generated with AI' alone is a disclosure", () => {
  // kills D8
  assert.equal(checkDisclosures("Drafted with care and generated with AI.", AI).allowed, true);
});

test("the guard is stateless across calls — no regex lastIndex carry-over", () => {
  // A regression guard: adding a /g flag to any pattern would make .test() alternate results.
  const text = "Sponsored. #AI";
  const results = Array.from({ length: 4 }, () => checkDisclosures(text, { ...AD, ...AI }).allowed);
  assert.deepEqual(results, [true, true, true, true]);
});

// Fixed DEFECT-1: the guard used to accept the literal opposite of a disclosure.
test("a NEGATED ad marker is not a disclosure", () => {
  for (const text of [
    "This post is not sponsored.",
    "This article contains no affiliate links.",
    "Not a paid partnership.",
    "This isn't sponsored.",
    "This isn’t sponsored.", // curly apostrophe, as word processors write it
    "We never accept sponsored posts.",
    "Written without affiliate links.",
    "A non-sponsored review.",
    "There are zero affiliate links here.",
    "Neither sponsored nor paid.",
    "Nor sponsored in any sense.",
  ]) {
    assert.equal(checkDisclosures(text, AD).allowed, false, `must not pass: "${text}"`);
  }
});

test("a NEGATED AI marker is not a disclosure", () => {
  for (const text of ["This review was not AI-generated.", "Written by hand, not generated by AI.", "No #AI was used."]) {
    assert.equal(checkDisclosures(text, AI).allowed, false, `must not pass: "${text}"`);
  }
});

test("a negation elsewhere does not cancel a real disclosure", () => {
  // Scope: only the few words before a marker, and only within its own clause. These are all
  // genuine disclosures that also contain a negation somewhere else.
  for (const text of [
    "No purchase necessary, sponsored content.",
    "Not every link here pays us. This one is an affiliate link.",
    "This post is sponsored. It is not a scam.",
    "Not sponsored in part, but this section is sponsored.",
    "There is no doubt this is sponsored.", // "no" is 4 words back: beyond the negation reach
  ]) {
    assert.equal(checkDisclosures(text, AD).allowed, true, `must pass: "${text}"`);
  }
});

test("documented limitation: a negation four or more words back is not caught", () => {
  // The README states this residual explicitly. If the heuristic is improved to catch it, this test
  // fails on purpose — update the README's limitation sentence, then flip the assertion.
  assert.equal(checkDisclosures("This is not in any way sponsored.", AD).allowed, true);
});

test("one un-negated marker is enough, even when another is negated", () => {
  assert.equal(checkDisclosures("Not a paid partnership, but it does contain affiliate links.", AD).allowed, true);
});

test(
  "'#ad-free' and '#ai-free' are not disclosures",
  { todo: "DEFECT-2 (medium): the trailing \\b matches at a hyphen, so #ad-free and #ai-free count as markers" },
  () => {
    assert.equal(checkDisclosures("Enjoy the #ad-free edition.", AD).allowed, false);
    assert.equal(checkDisclosures("Proudly #ai-free writing.", AI).allowed, false);
  },
);

test(
  "a marker the reader cannot see is not a disclosure",
  { todo: "DEFECT-3 (medium, undocumented limitation): markers inside HTML comments count, though they never render" },
  () => {
    assert.equal(checkDisclosures("<!-- #ad --> Buy the Pro plan today.", AD).allowed, false);
  },
);

test(
  "requireLiterals given a string (not an array) still requires the whole phrase",
  { todo: "DEFECT-4 (low): a string is iterated per CHARACTER, so text containing every letter passes without the phrase" },
  () => {
    const rules = { requireLiterals: "Results may vary" as unknown as string[] };
    // Contains every character of the phrase, but not the phrase.
    const d = checkDisclosures("Your mileage may vary; results differ.", rules);
    assert.equal(d.allowed, false);
  },
);

// ── approval gate ───────────────────────────────────────────────────────────

test("an item that is already released cannot be released again", () => {
  // kills A1: the already_released path had no test.
  const d = evaluateRelease({ status: "released", releasedBy: "operator@example.com" });
  assert.equal(d.allowed, false);
  assert.equal(d.reason, "already_released");
});

test("each known terminal status keeps its own reason, not the generic unknown_status", () => {
  // Kills A4: once the allow-list existed, deleting the "rejected" branch no longer made a rejected
  // item publishable — only its reason changed. Callers can branch on these codes, so pin them.
  const by = "operator@example.com";
  assert.equal(evaluateRelease({ status: "rejected", releasedBy: by }).reason, "already_rejected");
  assert.equal(evaluateRelease({ status: "retracted", releasedBy: by }).reason, "already_retracted");
  assert.equal(evaluateRelease({ status: "released", releasedBy: by }).reason, "already_released");
});

// Fixed DEFECT-5: the gate was a deny-list, so any status it did not recognise published.
test("only a PENDING item can be released — unknown or mis-cased statuses fail closed", () => {
  for (const status of ["REJECTED", " rejected", "Retracted", "archived", "PENDING", " pending", undefined, null, ""]) {
    const d = evaluateRelease({ status: status as never, releasedBy: "operator@example.com" });
    assert.equal(d.allowed, false, `status ${JSON.stringify(status)} must not publish`);
    assert.equal(d.reason, "unknown_status", `status ${JSON.stringify(status)}`);
  }
});

test(
  "a non-string releaser gets a decision, not an exception",
  { todo: "DEFECT-6 (medium): releasedBy = 42 (an integer user id) throws TypeError — the caller's catch block, not the gate, then decides" },
  () => {
    assert.doesNotThrow(() => evaluateRelease({ status: "pending", releasedBy: 42 as unknown as string }));
  },
);

// ── budget gate and cost estimation ─────────────────────────────────────────

test("an infinite recorded spend blocks", () => {
  assert.equal(evaluateBudget({ spentUsd: Number.POSITIVE_INFINITY, capUsd: 1 }).allowed, false);
});

// Fixed DEFECT-7: float accumulation left exact-cap spend a hair UNDER the cap.
test("spending exactly the default cap in small calls blocks the next call", () => {
  let spent = 0;
  for (let i = 0; i < 10; i++) spent += 0.1;
  assert.ok(spent < DEFAULT_HARD_CAP_USD, "precondition: ten 0.1s really do sum to just under 1.00");
  const d = evaluateBudget({ spentUsd: spent, capUsd: DEFAULT_HARD_CAP_USD });
  assert.equal(d.allowed, false, `spent ${spent} of ${DEFAULT_HARD_CAP_USD}`);
  assert.equal(d.reason, "cap_exceeded");
});

test("the tolerance is a billionth of a dollar, not a real allowance", () => {
  // A cent below the cap is still genuinely below it.
  assert.equal(evaluateBudget({ spentUsd: 0.99, capUsd: 1 }).allowed, true);
  assert.equal(evaluateBudget({ spentUsd: 0.999999, capUsd: 1 }).allowed, true);
});

test(
  "an infinite cap is not treated as unlimited",
  { todo: "DEFECT-8 (medium): capUsd = Infinity is accepted as a real cap, so nothing is ever blocked — contradicting 'never to unlimited'" },
  () => {
    assert.equal(evaluateBudget({ spentUsd: 1e9, capUsd: Number.POSITIVE_INFINITY }).allowed, false);
  },
);

test(
  "a corrupt (NaN) spend reading fails closed, as the loop gate does for its counter",
  { todo: "DEFECT-9 (medium): NaN spend reads as $0 and is ALLOWED; the loop gate blocks the same corruption — the two gates disagree" },
  () => {
    assert.equal(evaluateBudget({ spentUsd: Number.NaN, capUsd: 0.32 }).allowed, false);
  },
);

// Fixed DEFECT-10: an unreadable token count used to cost $0, so a provider response with no
// usage accrued nothing — silent free inference. It is now unbounded, the same posture as
// estimateMaxCostUsd for an unbounded output: a cost that cannot be read cannot read as free.
test("an unreadable token count is priced as unbounded, never as free", () => {
  for (const tokens of [Number.NaN, undefined, null, -1, "1000", Number.POSITIVE_INFINITY]) {
    assert.equal(
      estimateCostUsd("llama-3.3-70b", tokens as unknown as number),
      Number.POSITIVE_INFINITY,
      `tokens=${JSON.stringify(tokens)} must not be priced as a real number`,
    );
  }
});

test("a real zero is still zero, and a free model is still free whatever the count", () => {
  assert.equal(estimateCostUsd("llama-3.3-70b", 0), 0);
  // A zero-cost model costs nothing regardless of usage, so unreadable usage cannot matter there.
  assert.equal(estimateCostUsd("@cf/meta/llama-3.1-8b-instruct", Number.NaN), 0);
});

test(
  "an empty model name is priced like any unknown model, not as free",
  { todo: "DEFECT-11 (medium): estimateCostUsd('', n) returns 0, though the file's contract is 'unknown models are priced, not skipped'" },
  () => {
    assert.ok(estimateCostUsd("", 1000) > 0);
  },
);

test(
  "a negative price never produces a negative cost",
  { todo: "DEFECT-12 (low): a caller-supplied table with a negative rate returns a negative cost, which an unguarded accrual would SUBTRACT" },
  () => {
    assert.ok(estimateCostUsd("custom", 1000, { custom: -1 }) >= 0);
  },
);

// ── reservation gate ────────────────────────────────────────────────────────

test("drifted at-cap spend refuses even a zero-cost reservation", () => {
  // Isolates the reservation gate's own cap_exceeded tolerance from the admission tolerance.
  let spent = 0;
  for (let i = 0; i < 10; i++) spent += 0.1; // 0.9999999999999999
  const d = evaluateReservation({ spentUsd: spent, reservedUsd: 0, capUsd: 1 }, 0);
  assert.equal(d.allowed, false);
  assert.equal(d.reason, "cap_exceeded");
});

test(
  "an infinite cap is not treated as unlimited by reservations either",
  { todo: "DEFECT-8 (medium): same as the budget gate — capUsd = Infinity admits any reservation" },
  () => {
    const d = evaluateReservation({ spentUsd: 1e6, reservedUsd: 0, capUsd: Number.POSITIVE_INFINITY }, 1);
    assert.equal(d.allowed, false);
  },
);

test(
  "corrupt (NaN) outstanding holds do not read as zero holds",
  { todo: "DEFECT-9 (medium): reservedUsd = NaN reads as $0 of holds, so a full window admits new calls" },
  () => {
    const d = evaluateReservation({ spentUsd: 0.3, reservedUsd: Number.NaN, capUsd: 0.32 }, 0.01);
    assert.equal(d.allowed, false);
  },
);

test(
  "an unreadable prompt size cannot be bounded, so it cannot be reserved",
  { todo: "DEFECT-13 (low): NaN promptTokens is priced as 0 prompt tokens and silently UNDER-reserves, while a bad maxOutputTokens correctly returns Infinity" },
  () => {
    assert.equal(estimateMaxCostUsd("llama-3.3-70b", Number.NaN, 1000), Number.POSITIVE_INFINITY);
  },
);

// ── loop breaker ────────────────────────────────────────────────────────────

test(
  "a negative iteration counter is corrupt and fails closed",
  { todo: "DEFECT-14 (low): iteration = -5 is clamped to 0 and allowed; the file's own rule is that a corrupt counter must block" },
  () => {
    assert.equal(evaluateLoop({ iteration: -5, maxIterations: 10 }).allowed, false);
  },
);

test(
  "a three-agent cycle (A → B → C → A) is detected before the iteration cap",
  { todo: "LIMITATION (documented scope): the oscillation detector only recognises 2-cycles; a 3-cycle runs until maxIterations" },
  () => {
    const cycle = ["research:q", "analyze:q", "verify:q"];
    const recentActions = [...cycle, ...cycle, ...cycle];
    assert.equal(evaluateLoop({ iteration: 9, maxIterations: 50, recentActions }).allowed, false);
  },
);
